@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Siemens ModelSim Simulator
REM Description : Script for compiling the simulation design source files
REM
REM Generated by Vivado on Thu Apr 02 16:08:39 +0800 2026
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
set bin_path=D:\\modelsim10.7\\modelsim\\modelsim_software\\win64
call %bin_path%/vsim  -c -do "do {testbench_compile.do}" -l compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
