# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/IEEE2027/yolov5_accelerator/ip/bbuf/bbuf.xci
# IP: The module: 'bbuf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/IEEE2027/yolov5_accelerator/ip/bbuf/bbuf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bbuf'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/IEEE2027/yolov5_accelerator/ip/bbuf/bbuf.xci
# IP: The module: 'bbuf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/IEEE2027/yolov5_accelerator/ip/bbuf/bbuf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bbuf'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
