# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/IEEE2027/yolov5_accelerator/ip/rbuf_1/rbuf.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rbuf || ORIG_REF_NAME==rbuf} -quiet] -quiet
