# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/IEEE2027/yolov5_accelerator/yolov5_accelerator.runs/synth_1/yolo_sim_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param simulator.modelsimInstallPath D:/modelsim10.7/modelsim/modelsim_software/win64
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z100ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/IEEE2027/yolov5_accelerator/yolov5_accelerator.cache/wt [current_project]
set_property parent.project_path E:/IEEE2027/yolov5_accelerator/yolov5_accelerator.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/IEEE2027/yolov5_accelerator/yolov5_accelerator.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  E:/IEEE2027/yolov5_accelerator/src/cdma/src/accel_cdma_domain_top.v
  E:/IEEE2027/yolov5_accelerator/src/cdma/src/b_cdma_recv_data.v
  E:/IEEE2027/yolov5_accelerator/src/cdma/src/b_cdma_send_cmd.v
  E:/IEEE2027/yolov5_accelerator/src/cdma/src/b_cdma_top.v
  E:/IEEE2027/yolov5_accelerator/src/cbuf/src/bbuf_dat_top.v
  E:/IEEE2027/yolov5_accelerator/src/cacc/src/bbuf_prefetcher.v
  E:/IEEE2027/yolov5_accelerator/src/cacc/src/cacc_core.v
  E:/IEEE2027/yolov5_accelerator/src/cacc/src/cacc_requant.v
  E:/IEEE2027/yolov5_accelerator/src/cacc/src/cacc_top.v
  E:/IEEE2027/yolov5_accelerator/src/cbuf/src/cbuf_dat_top.v
  E:/IEEE2027/yolov5_accelerator/src/cdma/src/cdma_read_req.v
  E:/IEEE2027/yolov5_accelerator/src/cdma/src/cdma_top.v
  E:/IEEE2027/yolov5_accelerator/src/SPU/src/cmac_8.v
  E:/IEEE2027/yolov5_accelerator/src/SPU/src/cmac_array.v
  E:/IEEE2027/yolov5_accelerator/src/SPU/src/cmac_row.v
  E:/IEEE2027/yolov5_accelerator/src/cdma/src/cmda_rx_write.v
  E:/IEEE2027/yolov5_accelerator/src/CSC/src/csc_top.v
  E:/IEEE2027/yolov5_accelerator/src/mcif/fifo_dff.v
  E:/IEEE2027/yolov5_accelerator/src/mcif/hs_pipe.v
  E:/IEEE2027/yolov5_accelerator/src/mcif/mcif_4r_4w.v
  E:/IEEE2027/yolov5_accelerator/src/mcif/mcif_arb_comb4.v
  E:/IEEE2027/yolov5_accelerator/src/mcif/mcif_rd_4r.v
  E:/IEEE2027/yolov5_accelerator/src/mcif/mcif_rr_arb4.v
  E:/IEEE2027/yolov5_accelerator/src/mcif/mcif_wr_4w.v
  E:/IEEE2027/yolov5_accelerator/src/cbuf/src/mem_domain_top.v
  E:/IEEE2027/yolov5_accelerator/src/obuf/src/obuf_dat_top.v
  E:/IEEE2027/yolov5_accelerator/src/pool/src/pool_top.v
  E:/IEEE2027/yolov5_accelerator/src/SPU/src/simd_mac_dsp.v
  E:/IEEE2027/yolov5_accelerator/src/cdma/src/w_cdma_recv_data.v
  E:/IEEE2027/yolov5_accelerator/src/cdma/src/w_cdma_send_cmd.v
  E:/IEEE2027/yolov5_accelerator/src/cdma/src/w_cdma_top.v
  E:/IEEE2027/yolov5_accelerator/src/cbuf/src/wbuf_top.v
  E:/IEEE2027/yolov5_accelerator/src/WDMA/src/wdma_core.v
  E:/IEEE2027/yolov5_accelerator/src/CSR/yolo_global_fsm.v
  E:/IEEE2027/yolov5_accelerator/src/CSR/yolo_top.v
  E:/IEEE2027/yolov5_accelerator/src/CSR/yolo_sim_top.v
}
read_ip -quiet E:/IEEE2027/yolov5_accelerator/ip/wbuf_1/wbuf.xci
set_property used_in_implementation false [get_files -all e:/IEEE2027/yolov5_accelerator/ip/wbuf_1/wbuf_ooc.xdc]

read_ip -quiet E:/IEEE2027/yolov5_accelerator/ip/cbuf/cbuf.xci
set_property used_in_implementation false [get_files -all e:/IEEE2027/yolov5_accelerator/ip/cbuf/cbuf_ooc.xdc]

read_ip -quiet E:/IEEE2027/yolov5_accelerator/ip/bbuf/bbuf.xci
set_property used_in_implementation false [get_files -all e:/IEEE2027/yolov5_accelerator/ip/bbuf/bbuf_ooc.xdc]

read_ip -quiet E:/IEEE2027/yolov5_accelerator/ip/o_buf/o_buf.xci
set_property used_in_implementation false [get_files -all e:/IEEE2027/yolov5_accelerator/ip/o_buf/o_buf_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top yolo_sim_top -part xc7z100ffg900-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef yolo_sim_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file yolo_sim_top_utilization_synth.rpt -pb yolo_sim_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
