`timescale 1ns / 1ps

module accel_cdma_domain_top_cat #(
    parameter BANK_NUM            = 8,
    parameter REGION_W            = 8,
    parameter AXI_DATA_WIDTH      = 128,
    parameter MAX_BURST_LEN       = 256,
    parameter LOG2_MAX_BURST_LEN  = $clog2(MAX_BURST_LEN),
    parameter ROW_BLOCKS          = 8,
    parameter TK_IN               = 8,
    parameter N                   = 8,
    parameter BBUF_ADDR_W         = 9
)(
    input  wire                               clk,
    input  wire                               rst_n,

    input  wire                               w_start,
    output wire                               w_done,
    input  wire [27:0]                        cfg_wt_total_beats,
    input  wire [31:0]                        cfg_wt_base_addr,
    input  wire [15:0]                        cfg_total_co_groups,
    input  wire [15:0]                        cfg_coords_per_region,
    input  wire [3:0]                         cfg_active_banks,
    input  wire                               cfg_is_odd_oc,
    output wire                               w_rd_req_vld,
    input  wire                               w_rd_req_rdy,
    output wire [31 + LOG2_MAX_BURST_LEN:0]   w_rd_req_pd,
    input  wire                               w_rd_resp_vld,
    output wire                               w_rd_resp_rdy,
    input  wire [AXI_DATA_WIDTH-1:0]          w_rd_resp_pd,
    input  wire                               wbuf_can_write,
    output wire [BANK_NUM-1:0]                wbuf_wr_bank_en,
    output wire [REGION_W-1:0]                wbuf_wr_offset,
    output wire [AXI_DATA_WIDTH-1:0]          wbuf_wr_dat,
    output wire                               wbuf_wr_region_done,

    input  wire                               f_start,
    input  wire [31:0]                        cfg_f_base_addr,
    input  wire [15:0]                        cfg_f_width,
    input  wire [15:0]                        cfg_f_height,
    input  wire [15:0]                        cfg_f_ch_groups,
    input  wire                               cfg_f_cat_en,
    input  wire                               cfg_f_cat_src0_upsample,
    input  wire [31:0]                        cfg_f_cat_src1_base_addr,
    input  wire [15:0]                        cfg_f_cat_src0_ch_groups,
    input  wire [31:0]                        cfg_f_cat_src0_line_stride,
    input  wire [31:0]                        cfg_f_cat_src1_line_stride,
    input  wire [31:0]                        cfg_f_cat_src0_surface_stride,
    input  wire [31:0]                        cfg_f_cat_src1_surface_stride,
    input  wire                               f_rd_row_free,
    input  wire [3:0]                         f_rd_free_num,
    input  wire                               f_mcif_req_rdy,
    output wire                               f_mcif_req_vld,
    output wire [39:0]                        f_mcif_req_pd,
    input  wire                               f_mcif_rx_vld,
    input  wire [2*TK_IN*N-1:0]               f_mcif_rx_dat,
    output wire                               f_mcif_rx_rdy,
    output wire                               cbuf_wr_en,
    output wire [15:0]                        cbuf_wr_row,
    output wire [15:0]                        cbuf_wr_col_blk,
    output wire [15:0]                        cbuf_wr_ch_grp,
    output wire [BANK_NUM-1:0]                cbuf_wr_bank_en,
    output wire [BANK_NUM*TK_IN*N-1:0]        cbuf_wr_bank_dat,
    output wire                               cbuf_wr_row_done,

    input  wire                               b_start,
    output wire                               b_done,
    input  wire [31:0]                        cfg_b_base_addr,
    input  wire [15:0]                        cfg_b_out_channels,
    output wire                               b_rd_req_vld,
    input  wire                               b_rd_req_rdy,
    output wire [31 + LOG2_MAX_BURST_LEN:0]   b_rd_req_pd,
    input  wire                               b_rd_resp_vld,
    output wire                               b_rd_resp_rdy,
    input  wire [AXI_DATA_WIDTH-1:0]          b_rd_resp_pd,
    output wire [BANK_NUM-1:0]                bbuf_wr_en,
    output wire [BBUF_ADDR_W-1:0]             bbuf_wr_addr,
    output wire [BANK_NUM*64-1:0]             bbuf_wr_dat
);

    w_cdma_top #(
        .BANK_NUM(BANK_NUM),
        .REGION_W(REGION_W),
        .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
        .MAX_BURST_LEN(MAX_BURST_LEN),
        .LOG2_MAX_BURST_LEN(LOG2_MAX_BURST_LEN)
    ) u_w_cdma (
        .clk                  (clk),
        .rst_n                (rst_n),
        .start                (w_start),
        .done                 (w_done),
        .cfg_wt_total_beats   (cfg_wt_total_beats),
        .cfg_wt_base_addr     (cfg_wt_base_addr),
        .cfg_total_co_groups  (cfg_total_co_groups),
        .cfg_coords_per_region(cfg_coords_per_region),
        .cfg_active_banks     (cfg_active_banks),
        .cfg_is_odd_oc        (cfg_is_odd_oc),
        .rd_req_vld           (w_rd_req_vld),
        .rd_req_rdy           (w_rd_req_rdy),
        .rd_req_pd            (w_rd_req_pd),
        .rd_resp_vld          (w_rd_resp_vld),
        .rd_resp_rdy          (w_rd_resp_rdy),
        .rd_resp_pd           (w_rd_resp_pd),
        .wbuf_can_write       (wbuf_can_write),
        .wbuf_wr_bank_en      (wbuf_wr_bank_en),
        .wbuf_wr_offset       (wbuf_wr_offset),
        .wbuf_wr_dat          (wbuf_wr_dat),
        .wbuf_wr_region_done  (wbuf_wr_region_done)
    );

    cdma_top_cat #(
        .ROW_BLOCKS(ROW_BLOCKS),
        .BANK_NUM  (BANK_NUM),
        .TK_IN     (TK_IN),
        .N         (N)
    ) u_f_cdma (
        .clk                        (clk),
        .rst_n                      (rst_n),
        .start                      (f_start),
        .cfg_base_addr              (cfg_f_base_addr),
        .cfg_width                  (cfg_f_width),
        .cfg_height                 (cfg_f_height),
        .cfg_ch_groups              (cfg_f_ch_groups),
        .cfg_cat_en                 (cfg_f_cat_en),
        .cfg_cat_src0_upsample      (cfg_f_cat_src0_upsample),
        .cfg_cat_src1_base_addr     (cfg_f_cat_src1_base_addr),
        .cfg_cat_src0_ch_groups     (cfg_f_cat_src0_ch_groups),
        .cfg_cat_src0_line_stride   (cfg_f_cat_src0_line_stride),
        .cfg_cat_src1_line_stride   (cfg_f_cat_src1_line_stride),
        .cfg_cat_src0_surface_stride(cfg_f_cat_src0_surface_stride),
        .cfg_cat_src1_surface_stride(cfg_f_cat_src1_surface_stride),
        .rd_row_free                (f_rd_row_free),
        .rd_free_num                (f_rd_free_num),
        .mcif_req_rdy               (f_mcif_req_rdy),
        .mcif_req_vld               (f_mcif_req_vld),
        .mcif_req_pd                (f_mcif_req_pd),
        .mcif_rx_vld                (f_mcif_rx_vld),
        .mcif_rx_dat                (f_mcif_rx_dat),
        .mcif_rx_rdy                (f_mcif_rx_rdy),
        .wr_en                      (cbuf_wr_en),
        .wr_row                     (cbuf_wr_row),
        .wr_col_blk                 (cbuf_wr_col_blk),
        .wr_ch_grp                  (cbuf_wr_ch_grp),
        .wr_bank_en                 (cbuf_wr_bank_en),
        .wr_bank_dat                (cbuf_wr_bank_dat),
        .wr_row_done                (cbuf_wr_row_done)
    );

    b_cdma_top #(
        .BANK_NUM           (BANK_NUM),
        .AXI_DATA_WIDTH     (AXI_DATA_WIDTH),
        .MAX_BURST_LEN      (MAX_BURST_LEN),
        .LOG2_MAX_BURST_LEN (LOG2_MAX_BURST_LEN),
        .BBUF_ADDR_W        (BBUF_ADDR_W)
    ) u_b_cdma (
        .clk             (clk),
        .rst_n           (rst_n),
        .start           (b_start),
        .done            (b_done),
        .cfg_b_base_addr (cfg_b_base_addr),
        .cfg_out_channels(cfg_b_out_channels),
        .rd_req_vld      (b_rd_req_vld),
        .rd_req_rdy      (b_rd_req_rdy),
        .rd_req_pd       (b_rd_req_pd),
        .rd_resp_vld     (b_rd_resp_vld),
        .rd_resp_rdy     (b_rd_resp_rdy),
        .rd_resp_pd      (b_rd_resp_pd),
        .bbuf_wr_en      (bbuf_wr_en),
        .bbuf_wr_addr    (bbuf_wr_addr),
        .bbuf_wr_dat     (bbuf_wr_dat)
    );

endmodule
