# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/IEEE2027/yolov5_accelerator/ip/rbuf/rbuf.xci
# IP: The module: 'rbuf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/IEEE2027/yolov5_accelerator/ip/rbuf/rbuf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rbuf'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/IEEE2027/yolov5_accelerator/ip/rbuf/rbuf.xci
# IP: The module: 'rbuf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/IEEE2027/yolov5_accelerator/ip/rbuf/rbuf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rbuf'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
